---
extends: default

ignore:
  - ansible_collections/

rules:
  line-length:
    max: 200
  document-start: disable
  truthy:
    check-keys: false
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
